### ISSUE TITLE
When testing on my machine, webserver has connection issues

### ISSUE THREAD

**Issue by sjefferson99** [somakeit/smib#1]
Launching webserver module fails to connect without specifying actual localhost IP in env file.
Even with local IP specified the homepage will not properly load.

**Comment by samcorky** [comment]
@sjefferson99 I am unable to reproduce this issue. Running it from the terminal (inside the venv) works as well as running from PyCharm.

Open a command prompt inside the `smib` directory and run `poetry shell`, That will attach the shell to the venv. Do the same in a second terminal. 

Then run the app by `python -m smib.slack` and `python -m smib.webserver`

**Comment by sjefferson99** [comment]
@sam57719 Same behaviour as in my vscode and cmd shell manually activating the venv.

Will be something system specific, I'll dig into it and see if I can work it out.

**Comment by sjefferson99** [comment]
@sam57719 

It works fine on my linux dev machine, so I suspect it is firewall related. Given I can use this for testing for now and ultimately we will deploy on docker containers that will need to get the networking right, we can simply document the appropriate firewall config if any on a pi OS on top of any docker config. I will close this issue as test environment specific and leave it as an exercise to the reader on how to expose the web socket correctly on their machine.

I see there are some commits on the associated branch, if you can delete or PR it as appropriate.

**Comment by sjefferson99** [comment]
Confirmed, allowing the python.exe app through the firewall for private networks works on windows.
In addition, seems vscode has some kind of firewall as this only works in command prompts and not the vscode built in terminal.
