### ISSUE TITLE
Central DB

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#11]
Store dynamic data e.g. channels, slack members, current open views
Another docker container running mysql, sqllite or something similar
Ideally compatible with a python ORM for ease of interface development e.g. SQLAlchemy

**Comment by samcorky** [comment]
MONGO DB IS A WINNER
python package: pymongo

**Comment by samcorky** [comment]
url_parser for DB urls

`make_url` from the `from sqlalchemy.engine.url import make_url` package

e.g.

```python
from sqlalchemy.engine.url import make_url
raw_url = "mysql+pymysql://username:password@host:3306/database_name?charset=utf8"
url = make_url(raw_url)
print(url.get_backend_name(),
       url.get_driver_name(),
       url.username,
       url.password,
       url.host,
       url.port,
       url.database,
       url.query)
```

**Comment by samcorky** [comment]
@sjefferson99 I would like some thoughts on approaches to this

I have a working example in `tests/mngo_contexct.py` which works with a single document (row) in a collection.

I personally think this is fine as you can have nested dictionaries/lists within one row. 

> ⚠️ Nested stuff not currently working at all for me :(

I think this is the cleanest and simplest UX for plugin developers

```python
# Sets the MongoDB Collection (table) - this can be done in the background or with a factory function
Database = SingleMongoDocument.set_collection('space_openclose')

# Define structure for data - defined per plugin - and re-usable across plugins
@dataclass
class SpaceState(Database):
    open: bool = False
    last_updated: datetime = datetime.now()
    open_closed_last_trigger: str = None


if __name__ == '__main__':
    space = SpaceState()

    # Any change updates in the DB immediatley
    space.open = True

    # Unless using the context manager - where the DB gets updated upon exit of the "with" block
    with space:
        print(space.open)
        space.open_closed_last_trigger = 'button'
        space.last_updated = datetime.datetime.now()
```

the `SpaceState` class could be extended with

```python
@dataclass
class SpaceState(Database):
    open: bool = False
    last_updated: datetime = datetime.now(tz=timezone.utc)
    motion: bool = False
    open_closed_last_trigger: str = None

    def toggle_open(self):
        self.open = not self.open
        self.open_closed_last_trigger = 'toggle'

    def set_space_open(self):
        self.open = True
        self.open_closed_last_trigger = 'button'

    def set_space_closed(self):
        self.open = False
        self.open_closed_last_trigger = 'button'
        
    def __setattr__(self, name, value):
        super().__setattr__(name, value)
        # Set the last_updated timestamp everytime an attribute changes
        if name != "last_updated":
            self.last_updated = datetime.now(tz=timezone.utc)
```

**Comment by sjefferson99** [comment]
@sam57719 Class structure looks good. You'll have to talk me through how it is interacting with mongodb on Wednesday, I can see the database is passed to the class but not used in a way I understand, maybe related to the decorator?

Would also discuss the last_trigger attribute. Seem sensible to log what called it but you're mixing function with toggle for implicit button on open and closed when it could be anything calling the function, when we confirm the use case we can ensure that makes sense to me.

**Comment by samcorky** [comment]
This was just a test - found scenarios where it doesn't work properly.

Might have to go with a raw mongo DB interface to start with - uses python
dictionaries.

**Comment by samcorky** [comment]
Found this great pymongo wrapper library (after a bunch of digging)

https://github.com/joshmarshall/mogo/tree/main

Looks almost exactly like I wanted to create.

Will have a go at it tonight and add it into the space state plugin

**Comment by samcorky** [comment]
https://github.com/joshmarshall/mogo/tree/main

I have implemented the space_open/closed plugin with this - pretty tidy

Need to have a chat with @sjefferson99 r.e. authentication - but I think that can come later as this is only internally accessible for the time being

**Comment by samcorky** [comment]
https://docs.python.org/3.10/library/contextlib.html#contextlib.contextmanager

Enhancement to use this inside a decorator. Will create example tomrorow if I have time. 

Need to test this mogo library with multiple plugins accessing differnt data at same time.
