### ISSUE TITLE
File based logging for SMIBHID

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#125]
SD Card module for SMIBHID pi pico devices to allow local storage of logs.

Useful for debugging issues with production installations. 

[SD Card breakout hardware](https://shop.pimoroni.com/products/adafruit-micro-sd-spi-or-sdio-card-breakout-board-3v-only)

I believe there is an existing micropython `sdcard` library. 

An alternative would be dumping files to a network drive but that relies on the network connection.

**Comment by sjefferson99** [comment]
I was thinking about this recently. If we store logs they should be local, however sd card storage is relatively complex for the value even with the existing libraries and relies on SPI. 

The flash on board is just as good as sd card for storage with simple file calls and log rotation and cheaper to just replace whole pico if writes are exhausted. There is logging logic in the pimoroni enviro project we can base it on.

Also, we can make file logging a config value and only enable if problems are being experienced to save write wear. A problem needs to happen at least twice (once after enabling logging) to be worth looking into.

**Comment by sjefferson99** [comment]
@sam57719  Propose we rename the issue to enable file based logging for SMIBHID and discuss the above for specific implementation.

**Comment by sjefferson99** [comment]
Started work on making logging module process one or more output handlers configurable in config.py and building a file output handler.
