### ISSUE TITLE
Capture which smibhid did the thing into the database

### ISSUE THREAD

**Issue by sjefferson99** [somakeit/smib#169]
Extends #118 to log in the database and not just the logs.
@sam57719 Captured so we don't lose it, but you will want to add thoughts on what you are logging in the db and how.

**Comment by samcorky** [comment]
Open to any and all ideas for logging and tracking of things

Currently only storing current state, and eventually data for the poll plugin.

We could track usage of the smibhid devices for certain events e.g. how many times space open/closed used by which door. 
Could also store the most recent device to trigger the space_open/close alongside the state
