### ISSUE TITLE
Have an API queryable space open state stored in slack server

### ISSUE THREAD

**Issue by sjefferson99** [somakeit/smib#18]
Where the SmibHID will have leds to reflect space open status for the space open and close buttons, this state should be tracked centrally and be available for any endpoints interacting with space open or closed rather than tracking locally. SmibHID can then regularly poll to ensure it's in sync and update the LED states accordingly.

**Comment by samcorky** [comment]
Probably as part of the `Central DB` issue

**Comment by sjefferson99** [comment]
I was thinking something like this. I've written the current code with this in mind although nothing specific implemented. Vague ideas are could have a HID at either end of the space and the async code could easily implement a 30 second poll state watcher and consume a state change push from the slack server. This way you could have every physical button and slack button working off one state so you could use any you want without confusion. Could also query the state for other purposes. 

If we implemented a motion sensor or other presence detection, I think it might be best to have it as supplementary information So state is open or close, but also there is motion sense recently, then logic or simply human reviewing can be built on top as needed.

**Comment by samcorky** [comment]
being implemented as part of #11 / #48

**Comment by sjefferson99** [comment]
Done in #48
