### ISSUE TITLE
Detect and log how many active connections there are. 

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#19]
The `hello` event dictionary contains a field called `num_connections`. This is how many active socket connections for the app exist. 

Log this to the console for visibility.

**Comment by samcorky** [comment]
@sjefferson99  I have some changes for this that I was experimenting with but is currently reliant on the #6 branch - is this where rebase comes in? create new branch for this issue and then rebase it on top of the logging branch?

**Comment by sjefferson99** [comment]
@sam57719 If you need the work done on the #6 branch in a new branch for this issue, you can simply choose to base this new branch off the other feature branch, no rebasing required. Click the "Change branch source" option in the create branch dialogue to select the other branch as the source.
