### ISSUE TITLE
Add option to drive GPIO from space state

### ISSUE THREAD

**Issue by sjefferson99** [somakeit/smib#237]
Ability to configure a GPIO pin as high or low when space state is open and vice versa when closed.
Use case driving hardware based on space state, in our example an air filter with a MOSFET switching a 12v supply.

**Comment by samcorky** [comment]
Would this be a new smibhid device that's connected to the air filter.
Eventually this can be triggered by mqtt.

**Comment by sjefferson99** [comment]
I am triggering the GPIO from the space open state, so mqtt would drive it once we move to mqtt for space state. It will be a few extra lines to fire the GPIO change on space state, but has scope to drive the pin entirely from new commands etc. Also not running it off the space state LED means it doesn't pulse the load when there is an error.

I have already built the new device on veroboard, planning to install tomorrow.

**Comment by samcorky** [comment]
Sounds like a cool idea!

Interested to see tomororw

Need to work out how to connect the networked LED sign as well

**Comment by sjefferson99** [comment]
Added a commit to the associated branch that *should* work, but late now and will test in the space tomorrow.
Sent you a pic of the board on slack and will probably update the docs with example board and circuit diagram as well.
