### ISSUE TITLE
Add a webserver to smibhid for admin purposes

### ISSUE THREAD

**Issue by sjefferson99** [somakeit/smib#248]
For somakeit/smibhid#23 and somakeit/smib#241 we need a webserver to provide an admin interface. Issue is to investigate adding one to the async loop and see if it can be supported without first implementing MQTT.

**Comment by samcorky** [comment]
https://randomnerdtutorials.com/raspberry-pi-pico-web-server-micropython/#raspberry-pi-pico-web-server-micropython-code

**Comment by sjefferson99** [comment]
I have a webserver from another project I will integrate based on tinyweb that I know works in a similar async loop.
https://github.com/sjefferson99/pico-environment-control/blob/develop/http/webserver.py
