### ISSUE TITLE
Ability to add to hours counter once already open

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#254]
SMIBHID feature suggestion: pressing the open button when the space is open should add time to the timer, or if no timer is currently set, set the timer

[Slack Message](https://somakeit.slack.com/archives/C0K0ENJG6/p1729625805356319?thread_ts=1729625805.356319&cid=C0K0ENJG6)

**Comment by sjefferson99** [comment]
@sam57719 There is no timer as such, it's just a post with hours open. You could have a timer implemented on the smib side and you can interpret the new hours open as top up or reset to new value as you like. That should be a new issue, this one deals with the SMIBHID element.

**Comment by samcorky** [comment]
raised #256 to cover SMIB element
