### ISSUE TITLE
Create physical button to announce space open in slack

### ISSUE THREAD

**Issue by sjefferson99** [somakeit/smib#3]
Probably Pico connected to physical button that launches API request to web server that calls same event as slack software button.

**Comment by sjefferson99** [comment]
@sam57719 Have a spare pico w, prototype board and JST connectors, so will put this together and some simple request code to fire the events on push button for open and closed. Will include current limited LED outputs for state as well based on last button press. Will raise an enhancement issue for storing current state in the slack server and having SmibHID poll it to allow it to reflect a unified space open state from all inputs rather than relying on a local state machine.

**Comment by sjefferson99** [comment]
Commits done to get it working. Needs better error handling from SMIB API and correct calls making in slackapi.py for open and close. Buttons need debouncing better and the space open and closed code in HID and slackAPI needs refactoring to be more efficient.

**Comment by samcorky** [comment]
Code looks good! Will have a proper look when I'm back on my PC!

**Comment by sjefferson99** [comment]
Error handling added, but still pending merge of correct status return in API code to test. Code as DRY as it will get for now. API calls were correct, code was fixed in API server. Only button debouncing remains.

**Comment by sjefferson99** [comment]
Turns out was catching both button transitions, debouncing was fine, this is now fixed, event only fires on button being pushed and not when released.
