### ISSUE TITLE
Store number of connections in db so it can be retrieved

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#44]
Related to #35 and #19 

Store this centrally and be able to query it

**Comment by samcorky** [comment]
Would need to also ensure to be able to get the updated version

**Comment by sjefferson99** [comment]
Not easily possible to determine number of connections, especially if multiple servers hosting multiple DBs. Cancel this and rely on developers checking server logs to ensure they are working on their server when executing from slack.
