### ISSUE TITLE
Ephemeral message when space-open-announce message

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#58]
Ephemeral message to user when they send message in space-open-announce channel reminding them of the buttons etc

**Comment by sjefferson99** [comment]
Would need to implement the space open for X hours functionality first as that is the other legitimate reason people write messages in that channel today.

**Comment by sjefferson99** [comment]
@sam57719 I see no one writing instead of button pressing aside from legitimate extra information like will be in for a few hours in an hour. I don't think this is required?

**Comment by samcorky** [comment]
Agree with this.

**Comment by sjefferson99** [comment]
Not required.
