### ISSUE TITLE
Add proper logging to entire app stack

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#6]
Use python logging module and external file config

Quick thoughts for logging:

- Log to console
- Log to file (rotating file handler - deletes after x days)
- Log errors/exceptions to a .jsonl (json lines file) so can be parsed later if needed.

**Comment by samcorky** [comment]
Added custom plugin logger factory so that the correct plugin is recorded in the log
Added custom log handler which creates the specified log directory automatically if it doesn't exist

**Comment by samcorky** [comment]
@sjefferson99 see above comment - shall we merge this into the develop branch?

**Comment by sjefferson99** [comment]
@sam57719 As per slack, I am unlikely to be able to get my head around the code you are changing and the code you are adding in the very near future to properly review, so the next best strategy is to test thoroughly that this branch works as expected before merging it in. I'll give it a bit more of test out, but the primary issue before was that log folder creation, so hopefully won't find anything else.

**Comment by sjefferson99** [comment]
@sam57719 I pulled the latest code and tried to run and got an error that aiohttp was missing. I see this is a pip install package and not listed in the poetry config, is this a missed dependency you've added?

**Comment by samcorky** [comment]
> @sam57719 I pulled the latest code and tried to run and got an error that aiohttp was missing. I see this is a pip install package and not listed in the poetry config, is this a missed dependency you've added?

Was getting this myself in docker. I've added it to my own docker compise and build which seem to be working
