### ISSUE TITLE
Mongo DB open to all hosts

### ISSUE THREAD

**Issue by sjefferson99** [somakeit/smib#77]
In the container startup logs:
smib-db-ui      | Server is open to allow connections from anyone (0.0.0.0)
smib-db-ui      | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
smib-db-ui      | Mongo Express server listening at http://0.0.0.0:8081

The db should be configured to only accept connections from localhost/the other containers.

**Comment by samcorky** [comment]
@sjefferson99 that `Server is open to allow connections from anyone (0.0.0.0)` is the UI - if set to localhost or something - then no one would be able to access it and it would be useless. I agree with the basic AUTH thing though

**Comment by sjefferson99** [comment]
@sam57719 Keep forgetting you put a UI on there. I'll cancel this one as auth on the other issue should be fine for access restriction on this for the data it stores.
