### ISSUE TITLE
Add/improve Swagger docs in fastapi

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#9]
Utilise the `fastapi` swagger documention capabilities

**Comment by samcorky** [comment]
@sjefferson99 you seem better at documentation than myself - any pointers? I cant think of the words to put (see the branch)

**Comment by sjefferson99** [comment]
@sam57719 Not being familiar with fastAPI or swagger beyond occasionally consuming it elsewhere, I'm not sure what the actual outcome of this issue will look like. Is it along the lines of if you go to /doc you get swagger and you can use it to make API calls (insert link to swagger general docs) or something more smib specific? Can discuss on Wednesday and get something written up.

**Comment by samcorky** [comment]
Mainly talking about the readme.md file - which is getting pulled into the head of the swagger docs
