### ISSUE TITLE
Improve log level usage in SMIB (not SMIBHID)

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#96]
Improve log level usage e.g. make info messages required information, and make debug messages useful information for debugging etc etc.

**Comment by sjefferson99** [comment]
@sam57719 What files require this specifically? SMIBHID should have correct info/warn/error levels in logging throughout.

**Comment by samcorky** [comment]
@sjefferson99 this is for the smib framework as it appears almost everything apart from the initial app configuration and startup is a debug message (apart from errors)
