### ISSUE TITLE
Uncertain Space State not being shown on SMIBHID device

### ISSUE THREAD

**Issue by samcorky** [somakeit/smib#98]
From the  smibhid/readme.md
> Flashes both space state LEDs at 2Hz if space state cannot be determined

LEDs did not flash on installed SMIBHID device, they just stayed off.

Might just need updating to latest changes.

**Comment by sjefferson99** [comment]
@sam57719 This was added in the last commit, you'll find this happens if you run up v1.0.0 on a test smibhid. The space device is not on that version yet. Expected behaviour for that version is both LEDs off.

**Comment by samcorky** [comment]
I thought as much - thought I'd just check. Will leave open to remind us to update the smibhid device

**Comment by sjefferson99** [comment]
@sam57719 To be clear, it is valid for both LEDs to be off, but that is when the state is successfully queried and returned as specifically none. However, if there is an error then you will get the 2Hz flash on both LEDs, but only on the latest firmware that is not yet on the Door SMIBHID.

**Comment by sjefferson99** [comment]
Patched firmware.
